# Change these first
owner: techeek # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Acorid15
    url: https://odoo15.acorid.cn
  - name: Acorid17
    url: https://odoo17.acorid.cn
  - name: baby-international
    url: https://www.baby-international.com
  - name: JAIA
    url: http://120.79.228.48
  - name: wuliucat
    url: http://od.wuliucat.com
  - name: lontry
    url: https://lontry.einfo-tech.com
  - name: qy-smt
    url: https://www.qy-smt.com
  - name: oppeincabinet
    url: http://oppeincabinet.ca
  - name: ruifeng
    url: https://ruifengcc.cn
  - name: ebs-erp
    url: http://www.ebs-erp.cn:8013
  - name: EMPower
    url: https://www.emlitpe.net
  - name: loyalcat
    url: https://www.loyalcat.cn
  - name: MJW
    url: http://202.96.173.134:8069
  - name: OTW
    url: https://www.otwtech.com.au
  - name: Sinefine
    url: https://www.sinefine.store
  - name: icintracom
    url: https://portal.icintracom.com.tw
  - name: E-bike
    url: http://erp.sparkcotech.com
  - name: XCMG
    url: http://odoo.xcmgpng.com
status-website:
  # cname: demo.upptime.js.org
  baseUrl: /upptime